# Generated by Django 4.0.3 on 2022-04-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalName', models.CharField(max_length=100)),
                ('PIN', models.CharField(db_column='class', max_length=6)),
                ('HospitalContact', models.IntegerField()),
                ('HospitalAddress', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
    ]
